### PR TITLE
initial cmake support / linux support; requres adjustments to mscv pr…

### PR DESCRIPTION
**Pull request by 0x17de**
This provides the basics for PR #1 - You can successfully compile and run the project under linux with this cmake file. With minor (rather only project organizational) adjustments it will run under windows as well. (I sadly currently can not contribute to the windows part of this PR)

Changes required:

- GL/glfw3.h is in GLFW/glfw3.h on linux? Were the files copied into the GL directory? Otherwise we require some #ifndef.
- The msvcpp project might need readjustments
- The find_library directive for irrklang will not work on windows - add some IRRKLANG_FOUND check and provide alternative path
- I did a simplified wrapper for ASSERT for linux. You maybe want to adjust it

Things i have found (MSVCPP seems to be a little sloppy and allows these):

- Always use / for includes
- Do not specialize templates inside the class body
- Use < > for external includes, " " for includes of your project (okayish)
- Passing "glm::ivec& position" as non const reference into make_unique at src/scenes/GameScene.cpp:76
- Using Camera:: inside the class declaration (see changes to Camera.h)

Things i have not corrected and are worth of another PR:

- warning: "cast to pointer from integer of different size" for "glVertexAttribPointer": (const void*)offset

@hrishabh23 feel free to create a PR which is to be merged onto this branch for windows support. I can review if the linux version still works or readjust.

### CODE REVIEW

**Comment by 0x17de** [comment]
Oh and btw: well done so far :) Hope my comments didn't sound too harsh - i just want to inspire you with things i'd do. I didnt analyze code style and such yet - if you want i can also assist with that a little.

**Comment by MohabMohamed** [comment]
oh sorry for late response I was busy  I will take a look on the changes now

**Comment by MohabMohamed** [comment]
and thank you I really appreciate comments on the code :D 
and if you wanted to solve the warning or review the code style a pr is always welcome

**Comment by MohabMohamed** [comment]
@0x17de can't manage to build it as I get the following error message 

> /home/mohab/clion-2018.1.3/bin/cmake/bin/cmake --build /home/mohab/CLionProjects/BtatesCraft/cmake-build-debug --target BtatesCraft -- -j 4
[  5%] Linking CXX executable ../BtatesCraft/BtatesCraft
/usr/bin/ld: //usr/local/lib/libglfw3.a(posix_tls.c.o): undefined reference to symbol 'pthread_key_delete@@GLIBC_2.2.5'
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
CMakeFiles/BtatesCraft.dir/build.make:566: recipe for target '../BtatesCraft/BtatesCraft' failed
make[3]: *** [../BtatesCraft/BtatesCraft] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/BtatesCraft.dir/all' failed
make[2]: *** [CMakeFiles/BtatesCraft.dir/all] Error 2
CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/BtatesCraft.dir/rule' failed
make[1]: *** [CMakeFiles/BtatesCraft.dir/rule] Error 2
Makefile:118: recipe for target 'BtatesCraft' failed
make: *** [BtatesCraft] Error 2

**Comment by 0x17de** [comment]
@MohabMohamed it looks like i forgot find_package(Threads REQUIRED) and add ${CMAKE_THREAD_LIBS_INIT} to the LIBRARIES variable. you can try to add those changes - otherwise i could test and commit those changes by tomorrow

**Comment by MohabMohamed** [comment]
still getting the same error

**Pull request merged**
